baseurl = "https://example.com/"
languageCode = "en-US"
title = "Richard Boyd II"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"
  resume = "/:filename/"

[params]
  avatar = "headshot_small.jpg"
  author = "Richard Boyd II"
  description = "RichardBoydII.com"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[social]
  Keybase       = "richardboydii"
  Github        = "richardboydii"
  Email         = "me@richardboydii.com"
  LinkedIn      = "richardboydii"
  SlideShare    = "retr0grad3"
  Stackoverflow = "users/755735/richardboydii?tab=profile"
  Hackernews    = "retr0grad3"
  Reddit        = "retr0grad3"
  Meetup        = "15006291"
  Facebook      = "richinaustin"
  Twitter       = "richardboydii"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "https://countzer0.com"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"
[[menu.main]]
  name = "gpg key"
  identifier = "gpgkey"
  weight = 500
  url = "http://pgp.mit.edu/pks/lookup?op=get&search=0xBC0EBC00422DC2F9"