baseURL = "https://richardboydii.com/"
languageCode = "en-us"
title = "richardboydii.com"
theme = "smol"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[params]
  description = "The personal blog of Richard Boyd II."

[author]
  name = "Richard Boyd II"
  email = "me@richardboydii.com"

[permalinks]
  posts = "/:year/:month/:day/:title"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 4

  [[menu.main]]
        identifier = "blogroll"
        name = "Blogroll"
        url = "/blogroll/"
        weight = 5

  [[menu.main]]
        identifier = "rss"
        name = "RSS"
        url = "/posts/index.xml"
        weight = 6

# Footer
  [[menu.footer]]
        name = "Email"
        url = "mailto:me@richardboydii.com"
        pre = "<i class='fi-xnsuxl-close-envelope-solid'></i>"
        weight = 1
  [[menu.footer]]
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/richardboydii"
        pre = "<i class='fi-snsuxl-linkedin'></i>"
        weight = 2

  [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/richardboydii"
        pre = "<i class='fi-xnsuxl-twitter'></i>"
        weight = 3

  [[menu.footer]]
        name = "Github"
        url = "https://github.com/richardboydii"
        pre = "<i class='fi-xnsuxl-github'></i>"
        weight = 4

  [[menu.footer]]
        name = "Discogs"
        url = "https://www.discogs.com/user/richardboydii"
        pre = "<i class='fi-cnsdhl-radar-alt'></i>"
        weight = 5

  [[menu.footer]]
        name = "Mastodon"
        url = "https://www.discogs.com/user/richardboydii"
        pre = "<i class='fi-cnsdhl-radar-alt'></i>"
        weight = 6