version: 2
jobs:
  build:
    docker:
      - image: richardboydii/hugobuilder
    steps:
      - checkout
      - run:
          name: Update Submodules
          command: git submodule update --init --recursive
      - run:
          name: Build Static Site
          command: hugo -v -s src -d /project/build
      - run:
          name: Update S3 Bucket
          command: aws s3 sync /project/build s3://$BUCKET_NAME --delete;
      - run:
          name: Invalidate CloudFront Distribution
          command: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID  --paths "/*";
