baseURL = "https://richardboydii.com/"
languageCode = "en-us"
title = "richardboydii.com"
theme = "smol"

[params]
  author = "Richard Boyd II"
  description = "The personal blog of Richard Boyd II."

[permalinks]
  posts = "/:year/:month/:day/:title"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 4

  [[menu.main]]
        identifier = "blogroll"
        name = "Blogroll"
        url = "/blogroll/"
        weight = 5

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/richardboydii"
        pre = "<i class='fi-onsuxl-github-alt'></i>"
        weight = 1 